// <auto-generated />
using Frigo_API_DB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Frigo_API_DB.Migrations
{
    [DbContext(typeof(FridgeDbContext))]
    partial class FridgeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Frigo_API_DB.Hoeveelheid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Aantal")
                        .HasColumnType("int")
                        .HasColumnName("Aantal");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Naam");

                    b.HasKey("Id")
                        .IsClustered();

                    b.ToTable("Hoeveelheden");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aantal = 0,
                            Naam = "Cola-blik"
                        },
                        new
                        {
                            Id = 2,
                            Aantal = 0,
                            Naam = "Fanta"
                        },
                        new
                        {
                            Id = 3,
                            Aantal = 0,
                            Naam = "Sprite-Lemon-blik"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
